[2020-11-03 21:47:40,956][ThreadPoolExecutor-1_1:15428][task_id:django.request][log.py:228][ERROR][Internal Server Error: /a]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-11-03 21:47:40,996][django-main-thread:12752][task_id:django.channels.server][runserver.py:154][ERROR][HTTP GET /a 500 [0.04, 127.0.0.1:28770]]
[2020-11-04 09:27:01,374][ThreadPoolExecutor-1_0:22120][task_id:django.request][log.py:228][ERROR][Internal Server Error: /login]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2020-11-04 09:27:01,412][django-main-thread:19392][task_id:django.channels.server][runserver.py:154][ERROR][HTTP POST /login 500 [0.81, 10.129.9.2:59416]]
[2020-11-04 09:27:58,170][ThreadPoolExecutor-1_0:21584][task_id:django.request][log.py:228][ERROR][Internal Server Error: /login]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2020-11-04 09:27:58,173][django-main-thread:18456][task_id:django.channels.server][runserver.py:154][ERROR][HTTP POST /login 500 [2.77, 10.129.9.2:59444]]
[2020-11-04 09:29:36,600][ThreadPoolExecutor-1_0:18496][task_id:django.request][log.py:228][ERROR][Internal Server Error: /login]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2020-11-04 09:29:36,605][django-main-thread:21964][task_id:django.channels.server][runserver.py:154][ERROR][HTTP POST /login 500 [0.47, 10.129.9.2:59514]]
